# Run unit tests using CTest
name: CTests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  CMakeTests:
    runs-on: tonipes/sfml-docker

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: CMake build
      run: cd ConcurrentTetris; mkdir build && cd build; cmake --build .. --config Debug

    - name: Cmake test
      run: ctest .
      
    
    
