name: cppcheck

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install cppcheck
      run: sudo apt-get install cppcheck -y

    - name: Run cppcheck
      run: cppcheck --force --enable=all --error-exitcode=1 --output-file=cppcheck_results.txt .
      
    - name: Print cppcheck results
      if: success() || failure()
      run: cat cppcheck_results.txt

    - name: Archive cppcheck results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: Cppcheck Results
        path: cppcheck_results.txt

